name: Build Image and Push to Docker Hub

on:
  push:
    branches: [ "master" ]

jobs:
  build-push-docker-hub:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0

      # Instructions are taken from here: https://docs.docker.com/docker-for-mac/multi-arch/
      - name: Set up Docker
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name multiarch --driver docker-container --use
          docker buildx inspect --bootstrap

      - name: Build and push to Docker Hub
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/armhf \
            -t pitop/deb-build:latest \
            --push .
